import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  tutorialSidebar: [
    "index",
    "commandline",
    {
      type: "category",
      label: "Targets",
      items: [
        {
          type: "category",
          label: "type",
          items: [
            "targets/executable",
            "targets/static_library",
            "targets/shared_library",
            "targets/headeronly_library",
            "targets/prebuilt_library",
          ],
        },
        {
          type: "category",
          label: "config",
          items: [
            "targets/source",
            "targets/compile",
            "targets/link",
            "targets/properties",
            "targets/custom_target",
            "targets/public_private",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Variables",
      items: ["variables/variables", "variables/cache"],
    },
    {
      type: "category",
      label: "CmakeLists",
      items: [
        "cmakelists/if",
        "cmakelists/subdirs",
        "cmakelists/generator_expressions",
        "cmakelists/output",
        "cmakelists/source_group",
      ],
    },
    {
      type: "category",
      label: "Libs",
      items: [
        "libs/find_package",
        "libs/installing",
        "libs/fetch_content",
        "libs/zlib",
        "libs/stb",
        "libs/glfw",
        "libs/glew",
        "libs/ktx",
        "libs/openxr",
        "libs/gst",
        "libs/vulkan",
        "libs/boost",
        "libs/pkg-config",
        "libs/nlohmann_json",
        "libs/ssl",
      ],
    },
    {
      type: "category",
      label: "Install",
      link: { type: "doc", id: "install/index" },
      items: [
        "install/header",
        "install/export",
        "install/local_install",
      ]
    },
    {
      type: "category",
      label: "Tips",
      items: [
        "other/clangd",
        "other/gitignore",
        "other/vscode",
        "other/vswhere",
        "other/android_ndk",
        "other/vcpkg",
        "other/qt6",
        "other/python",
        "other/blender",
      ],
    },
  ],
};

export default sidebars;
