import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  tutorialSidebar: [
    "index",
    "commandline",
    {
      type: "category",
      label: "Target",
      items: [
        "basic/minimal",
        "basic/target",
        "basic/compile",
        "basic/link",
        "basic/properties",
        "basic/custom_target",
      ],
    },
    {
      type: "category",
      label: "CmakeLists",
      items: [
        "cmakelists/variables",
        "cmakelists/if",
        "cmakelists/subdirs",
        "cmakelists/generator_expressions",
        "cmakelists/fetch_content",
        "cmakelists/find_package",
        "cmakelists/output",
        "cmakelists/source_group",
      ],
    },
    {
      type: "category",
      label: "Tips",
      items: [
        "other/gitignore",
        "other/clangd",
        "other/vscode",
        "other/vswhere",
        "other/android_ndk",
        "other/vcpkg",
        "other/qt6",
        "other/python",
        "other/blender",
      ],
    },
  ],
};

export default sidebars;
