import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  tutorialSidebar: [
    "index",
    "commandline",
    {
      type: "category",
      label: "Targets",
      items: [
        {
          type: "category",
          label: "type",
          items: [
            "targets/executable",
            "targets/static_library",
            "targets/shared_library",
            "targets/headeronly_library",
            "targets/prebuilt_library",
          ],
        },
        {
          type: "category",
          label: "config",
          items: [
            "targets/source",
            "targets/compile",
            "targets/link",
            "targets/properties",
            "targets/custom_target",
            "targets/public_private",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Variables",
      items: ["variables/variables", "variables/cache"],
    },
    {
      type: "category",
      label: "CmakeLists",
      items: [
        "cmakelists/if",
        "cmakelists/subdirs",
        "cmakelists/generator_expressions",
        "cmakelists/output",
        "cmakelists/source_group",
      ],
    },
    {
      type: "category",
      label: "FetchContent",
      link: { type: "doc", id: "fetch_content/index" },
      items: [
        "fetch_content/zlib",
        "fetch_content/stb",
        "fetch_content/glfw",
        "fetch_content/glew",
        "fetch_content/glm",
        "fetch_content/ktx",
        "fetch_content/openxr",
        "fetch_content/gst",
        "fetch_content/vulkan",
        "fetch_content/boost",
        "fetch_content/pkg-config",
        "fetch_content/nlohmann_json",
        "fetch_content/ssl",
        "fetch_content/opencv",
        "fetch_content/cv_bridge",
      ],
    },
    {
      type: "category",
      label: "Find Package",
      link: { type: "doc", id: "find_package/index" },
      items: [
        "find_package/searchpath",
        "find_package/header",
        "find_package/export",
        "find_package/local_install",
      ],
    },
    {
      type: "category",
      label: "Tips",
      items: [
        "other/formatter",
        "other/clangd",
        "other/gitignore",
        "other/vscode",
        "other/vswhere",
        "other/android_ndk",
        "other/vcpkg",
        "other/qt5",
        "other/qt6",
        "other/python",
        "other/blender",
        "other/copy_dll",
        "other/toolchain",
      ],
    },
    {
      type: "category",
      label: "ROS2",
      link: { type: "doc", id: "ros2/index" },
      items: [
        "ros2/pixi",
        "ros2/colcon",
        "ros2/ros_api",
      ],
    },
  ],
};

export default sidebars;
